// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Velzon.Models;

namespace Velzon.Context;

public partial class CApp_SystemApp_System_BancobancoSQLitedbContext : DbContext
{
    public CApp_SystemApp_System_BancobancoSQLitedbContext()
    {
    }

    public CApp_SystemApp_System_BancobancoSQLitedbContext(DbContextOptions<CApp_SystemApp_System_BancobancoSQLitedbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tb_ator> tb_ator { get; set; }

    public virtual DbSet<tb_categoria_produto> tb_categoria_produto { get; set; }

    public virtual DbSet<tb_certificado_digital> tb_certificado_digital { get; set; }

    public virtual DbSet<tb_clasCont1> tb_clasCont1 { get; set; }

    public virtual DbSet<tb_clasCont2> tb_clasCont2 { get; set; }

    public virtual DbSet<tb_codigo_produto> tb_codigo_produto { get; set; }

    public virtual DbSet<tb_cont> tb_cont { get; set; }

    public virtual DbSet<tb_contExt> tb_contExt { get; set; }

    public virtual DbSet<tb_contExtGru> tb_contExtGru { get; set; }

    public virtual DbSet<tb_contExtSec> tb_contExtSec { get; set; }

    public virtual DbSet<tb_contExtSubGru> tb_contExtSubGru { get; set; }

    public virtual DbSet<tb_contGru> tb_contGru { get; set; }

    public virtual DbSet<tb_contSec> tb_contSec { get; set; }

    public virtual DbSet<tb_contSubGru> tb_contSubGru { get; set; }

    public virtual DbSet<tb_est> tb_est { get; set; }

    public virtual DbSet<tb_estados_br> tb_estados_br { get; set; }

    public virtual DbSet<tb_forma_pagamento> tb_forma_pagamento { get; set; }

    public virtual DbSet<tb_historico> tb_historico { get; set; }

    public virtual DbSet<tb_jornada> tb_jornada { get; set; }

    public virtual DbSet<tb_marca_produto> tb_marca_produto { get; set; }

    public virtual DbSet<tb_matriz> tb_matriz { get; set; }

    public virtual DbSet<tb_movimentacao> tb_movimentacao { get; set; }

    public virtual DbSet<tb_movimentacao_caixa> tb_movimentacao_caixa { get; set; }

    public virtual DbSet<tb_movimentacao_impressao> tb_movimentacao_impressao { get; set; }

    public virtual DbSet<tb_movimentacao_pagamento> tb_movimentacao_pagamento { get; set; }

    public virtual DbSet<tb_movimentacao_pagamento_parcela> tb_movimentacao_pagamento_parcela { get; set; }

    public virtual DbSet<tb_movimentacao_produto> tb_movimentacao_produto { get; set; }

    public virtual DbSet<tb_municipio> tb_municipio { get; set; }

    public virtual DbSet<tb_ncm> tb_ncm { get; set; }

    public virtual DbSet<tb_nfe> tb_nfe { get; set; }

    public virtual DbSet<tb_nfe_enviada_filial> tb_nfe_enviada_filial { get; set; }

    public virtual DbSet<tb_pais> tb_pais { get; set; }

    public virtual DbSet<tb_pdv> tb_pdv { get; set; }

    public virtual DbSet<tb_planCont> tb_planCont { get; set; }

    public virtual DbSet<tb_produto> tb_produto { get; set; }

    public virtual DbSet<tb_produto_filial> tb_produto_filial { get; set; }

    public virtual DbSet<tb_rede> tb_rede { get; set; }

    public virtual DbSet<tb_regioes_br> tb_regioes_br { get; set; }

    public virtual DbSet<tb_relacao_produto_cadastro_XML> tb_relacao_produto_cadastro_XML { get; set; }

    public virtual DbSet<tb_resEventoNFe> tb_resEventoNFe { get; set; }

    public virtual DbSet<tb_resposta_NFe> tb_resposta_NFe { get; set; }

    public virtual DbSet<tb_secao_produto> tb_secao_produto { get; set; }

    public virtual DbSet<tb_sub_forma_pagamento> tb_sub_forma_pagamento { get; set; }

    public virtual DbSet<tb_subcategoria_produto> tb_subcategoria_produto { get; set; }

    public virtual DbSet<tb_unidade_monetaria> tb_unidade_monetaria { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlite("Data Source=C:\\App_System\\App_System_Banco\\bancoSQLite.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}