// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_certificado_digital", Name = "ifk_tb_certificado_digital_tb_ator")]
[Index("fk_tb_estados_br", Name = "ifk_tb_estados_br_tb_ator")]
[Index("fk_tb_matriz", Name = "ifk_tb_matriz_tb_ator")]
[Index("fk_tb_municipio", Name = "ifk_tb_municipio_tb_ator")]
public partial class tb_ator
{
    [Key]
    public long id_ator { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string at_inscEstSubst { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_persTim { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_dirRede { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_dirMov { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] at_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] at_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] at_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] at_desat { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_genero { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_nfeIndInscEst { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_nfeCodRegTrib { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_atorTipo { get; set; }

    [Column(TypeName = "varchar(18)")]
    public string at_cnpj { get; set; }

    [Column(TypeName = "varchar(14)")]
    public string at_cpf { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string at_rgRne { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_idMl { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_razSoc { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_nomeFant { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_end_Logr { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_end_Num { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_end_Compl { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_end_Bairro { get; set; }

    public string at_end_PontoRef { get; set; }

    [Column(TypeName = "varchar(9)")]
    public string at_end_Cep { get; set; }

    public long? at_end_Mun { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string at_telFixo { get; set; }

    [Column(TypeName = "varchar(10)")]
    public string at_telFixoRamal { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string at_telCel { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_respon { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string at_inscEst { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string at_inscMun { get; set; }

    [Column(TypeName = "varchar(9)")]
    public string at_inscSuframa { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_email { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_website { get; set; }

    [Column(TypeName = "varchar(5)")]
    public string at_dtNasc { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_emailCont { get; set; }

    public string at_obsCom { get; set; }

    public string at_obsFisc { get; set; }

    [Column(TypeName = "varchar(12)")]
    public string at_cnae { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] at_prop { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] at_nfeCredSn { get; set; }

    [Column(TypeName = "varchar(100)")]
    public string at_nfeCscTokenProd { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_nfeCscIdProd { get; set; }

    [Column(TypeName = "varchar(100)")]
    public string at_nfeCscTokenHom { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_nfeCscIdHom { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] at_revenda { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_nfeEnqSN { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_nfeRecBrutaEnqSN { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] at_receitaBrutaTotal { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] at_receitaBrutaTotal_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long at_nfeTipoAmb { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] at_percComisAtend { get; set; }

    [Required]
    [Column(TypeName = "NUMERIC(10, 2)")]
    public byte[] at_metaMensal { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string at_nomeUsuario { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string at_senhaUsuarioHashCode { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] at_manutPdv { get; set; }

    public long? at_atorH { get; set; }

    public long? at_estH { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] at_canc { get; set; }

    public long? fk_tb_municipio { get; set; }

    public long? fk_tb_estados_br { get; set; }

    public long? fk_tb_certificado_digital { get; set; }

    public long? fk_tb_matriz { get; set; }

    [ForeignKey("fk_tb_certificado_digital")]
    [InverseProperty("tb_ator")]
    public virtual tb_certificado_digital fk_tb_certificado_digitalNavigation { get; set; }

    [ForeignKey("fk_tb_estados_br")]
    [InverseProperty("tb_ator")]
    public virtual tb_estados_br fk_tb_estados_brNavigation { get; set; }

    [ForeignKey("fk_tb_matriz")]
    [InverseProperty("tb_ator")]
    public virtual tb_matriz fk_tb_matrizNavigation { get; set; }

    [ForeignKey("fk_tb_municipio")]
    [InverseProperty("tb_ator")]
    public virtual tb_municipio fk_tb_municipioNavigation { get; set; }

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_certificado_digital> tb_certificado_digital { get; set; } = new List<tb_certificado_digital>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_cont> tb_cont { get; set; } = new List<tb_cont>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_historico> tb_historico { get; set; } = new List<tb_historico>();

    [InverseProperty("fk_tb_atorAtendNavigation")]
    public virtual ICollection<tb_movimentacao_produto> tb_movimentacao_produto { get; set; } = new List<tb_movimentacao_produto>();

    [InverseProperty("fk_tb_ator_atendNavigation")]
    public virtual ICollection<tb_movimentacao> tb_movimentacaofk_tb_ator_atendNavigation { get; set; } = new List<tb_movimentacao>();

    [InverseProperty("fk_tb_ator_destNavigation")]
    public virtual ICollection<tb_movimentacao> tb_movimentacaofk_tb_ator_destNavigation { get; set; } = new List<tb_movimentacao>();

    [InverseProperty("fk_tb_ator_emitNavigation")]
    public virtual ICollection<tb_movimentacao> tb_movimentacaofk_tb_ator_emitNavigation { get; set; } = new List<tb_movimentacao>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_pdv> tb_pdv { get; set; } = new List<tb_pdv>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_produto> tb_produto { get; set; } = new List<tb_produto>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_produto_filial> tb_produto_filial { get; set; } = new List<tb_produto_filial>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_relacao_produto_cadastro_XML> tb_relacao_produto_cadastro_XML { get; set; } = new List<tb_relacao_produto_cadastro_XML>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_resEventoNFe> tb_resEventoNFe { get; set; } = new List<tb_resEventoNFe>();

    [InverseProperty("fk_tb_atorNavigation")]
    public virtual ICollection<tb_resposta_NFe> tb_resposta_NFe { get; set; } = new List<tb_resposta_NFe>();
}