// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

public partial class tb_contExtSec
{
    [Key]
    public long id_contExtSec { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] ces_deb { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] ces_cred { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ces_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ces_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] ces_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] ces_canc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] ces_conc { get; set; }

    public long? fk_tb_contSec { get; set; }

    [ForeignKey("fk_tb_contSec")]
    [InverseProperty("tb_contExtSec")]
    public virtual tb_contSec fk_tb_contSecNavigation { get; set; }
}