// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_contSubGru", Name = "ifk_tb_contSubGru_tb_contExtSubGru")]
public partial class tb_contExtSubGru
{
    [Key]
    public long id_contExtSubGru { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] cesg_deb { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] cesg_cred { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cesg_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cesg_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] cesg_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cesg_canc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cesg_conc { get; set; }

    public long? fk_tb_contSubGru { get; set; }

    [ForeignKey("fk_tb_contSubGru")]
    [InverseProperty("tb_contExtSubGru")]
    public virtual tb_contSubGru fk_tb_contSubGruNavigation { get; set; }
}