// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_rede", Name = "ifk_tb_rede_tb_clasCont1")]
public partial class tb_clasCont1
{
    [Key]
    public long id_clasCont1 { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cc1_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cc1_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] cc1_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cc1_desat { get; set; }

    [Column(TypeName = "varchar(48)")]
    public string cc1_desc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cc1_saida { get; set; }

    public long? fk_tb_rede { get; set; }

    [ForeignKey("fk_tb_rede")]
    [InverseProperty("tb_clasCont1")]
    public virtual tb_rede fk_tb_redeNavigation { get; set; }
}