// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_cont")]
[Index("fk_tb_contSubGru", Name = "ifk_tb_contSubGru_tb_cont")]
public partial class tb_cont
{
    [Key]
    public long id_cont { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string ct_desc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] ct_saldo { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ct_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ct_dAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] ct_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] ct_canc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] ct_conc { get; set; }

    public long? fk_tb_ator { get; set; }

    public long? fk_tb_contSubGru { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_cont")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }

    [ForeignKey("fk_tb_contSubGru")]
    [InverseProperty("tb_cont")]
    public virtual tb_contSubGru fk_tb_contSubGruNavigation { get; set; }

    [InverseProperty("fk_tb_contNavigation")]
    public virtual ICollection<tb_contExt> tb_contExt { get; set; } = new List<tb_contExt>();
}