// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_produto", Name = "ifk_tb_produto_tb_codigo_produto")]
public partial class tb_codigo_produto
{
    [Key]
    public long id_codigo_produto { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cp_desat { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cp_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cp_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] cp_dtAcs { get; set; }

    [Column(TypeName = "varchar(14)")]
    public string cp_barras { get; set; }

    public long? fk_tb_produto { get; set; }

    [ForeignKey("fk_tb_produto")]
    [InverseProperty("tb_codigo_produto")]
    public virtual tb_produto fk_tb_produtoNavigation { get; set; }
}