// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_certificado_digital")]
public partial class tb_certificado_digital
{
    [Key]
    public long id_certificado_digital { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cd_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cd_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] cd_dtAcs { get; set; }

    [Column(TypeName = "varchar(18)")]
    public string cd_cnpj { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string cd_razSoc { get; set; }

    public byte[] cd_rawData { get; set; }

    [Column(TypeName = "varchar(64)")]
    public string cd_pwd { get; set; }

    [Column(TypeName = "varchar(128)")]
    public string cd_serial { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] cd_dtPub { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] cd_dtExp { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cd_ativo { get; set; }

    [Column(TypeName = "varchar(50)")]
    public string cd_tipo { get; set; }

    [Column(TypeName = "varchar(50)")]
    public string cd_modoEmissao { get; set; }

    [Column(TypeName = "INT")]
    public long cd_x509Version { get; set; }

    [Column(TypeName = "varchar(128)")]
    public string cd_sHA1String { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cd_canc { get; set; }

    public long? fk_tb_ator { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_certificado_digital")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }

    [InverseProperty("fk_tb_certificado_digitalNavigation")]
    public virtual ICollection<tb_ator> tb_ator { get; set; } = new List<tb_ator>();
}