// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

public partial class tb_contSec
{
    [Key]
    public long id_contSec { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cs_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] cs_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] cs_dtAcs { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string cs_desc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cs_canc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] cs_conc { get; set; }

    [InverseProperty("fk_tb_contSecNavigation")]
    public virtual ICollection<tb_contExtSec> tb_contExtSec { get; set; } = new List<tb_contExtSec>();
}