// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_secao_produto", Name = "ifk_tb_secao_produto_tb_categoria_produto")]
public partial class tb_categoria_produto
{
    [Key]
    public long id_categoria_produto { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime cp_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime cp_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public DateTime cp_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public int cp_desat { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string cp_desc { get; set; }

    public long? fk_tb_secao_produto { get; set; }

    [ForeignKey("fk_tb_secao_produto")]
    [InverseProperty("tb_categoria_produto")]
    public virtual tb_secao_produto fk_tb_secao_produtoNavigation { get; set; }

    [InverseProperty("fk_tb_categoria_produtoNavigation")]
    public virtual ICollection<tb_produto> tb_produto { get; set; } = new List<tb_produto>();

    [InverseProperty("fk_tb_categoria_produtoNavigation")]
    public virtual ICollection<tb_subcategoria_produto> tb_subcategoria_produto { get; set; } = new List<tb_subcategoria_produto>();
}