// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_contGru", Name = "ifk_tb_contGru_tb_contExtGru")]
public partial class tb_contExtGru
{
    [Key]
    public long id_contExtGru { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] ceg_deb { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] ceg_cred { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ceg_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ceg_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] ceg_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] ceg_canc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] ceg_conc { get; set; }

    public long? fk_tb_contGru { get; set; }

    [ForeignKey("fk_tb_contGru")]
    [InverseProperty("tb_contExtGru")]
    public virtual tb_contGru fk_tb_contGruNavigation { get; set; }
}