// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_regioes_br", Name = "ifk_tb_regioes_br_tb_estados_br")]
public partial class tb_estados_br
{
    [Key]
    public long id_estados_br { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] eb_desat { get; set; }

    [Column(TypeName = "tinyint")]
    public long? eb_id { get; set; }

    [Column(TypeName = "varchar(2)")]
    public string eb_sigla { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string eb_nome { get; set; }

    public long? fk_tb_regioes_br { get; set; }

    [ForeignKey("fk_tb_regioes_br")]
    [InverseProperty("tb_estados_br")]
    public virtual tb_regioes_br fk_tb_regioes_brNavigation { get; set; }

    [InverseProperty("fk_tb_estados_brNavigation")]
    public virtual ICollection<tb_ator> tb_ator { get; set; } = new List<tb_ator>();

    [InverseProperty("fk_tb_estados_brNavigation")]
    public virtual ICollection<tb_municipio> tb_municipio { get; set; } = new List<tb_municipio>();
}