// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_rede", Name = "ifk_tb_rede_tb_forma_pagamento")]
public partial class tb_forma_pagamento
{
    [Key]
    public long id_forma_pagamento { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] fp_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] fp_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] fp_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] fp_desat { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string fp_desc { get; set; }

    [Column(TypeName = "smallint")]
    public long fp_ordExib { get; set; }

    [Column(TypeName = "nchar(1)")]
    public string fp_atalhoTecl { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string fp_taxaDesc { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] fp_taxaData { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa0 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa1 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa2 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa3 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa4 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa5 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa6 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa7 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa8 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa9 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa10 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa11 { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] fp_taxa12 { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] fp_vlrMin { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] fp_vlrMax { get; set; }

    [Column(TypeName = "smallint")]
    public long fp_parcMin { get; set; }

    [Column(TypeName = "smallint")]
    public long fp_parcMax { get; set; }

    [Column(TypeName = "smallint")]
    public long fp_intParcBase { get; set; }

    [Column(TypeName = "INT")]
    public long fp_nfeIndPag { get; set; }

    [Column(TypeName = "INT")]
    public long fp_nfeTipoPag { get; set; }

    [Column(TypeName = "tinyint")]
    public long fp_nfeTipoIntegr { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] fp_canc { get; set; }

    public long? fk_tb_rede { get; set; }

    [ForeignKey("fk_tb_rede")]
    [InverseProperty("tb_forma_pagamento")]
    public virtual tb_rede fk_tb_redeNavigation { get; set; }

    [InverseProperty("fk_tb_forma_pagamentoNavigation")]
    public virtual ICollection<tb_sub_forma_pagamento> tb_sub_forma_pagamento { get; set; } = new List<tb_sub_forma_pagamento>();
}