// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_historico")]
[Index("fk_tb_est", Name = "ifk_tb_est_tb_historico")]
public partial class tb_historico
{
    [Key]
    public long id_historico { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] hi_dtCri { get; set; }

    [Column(TypeName = "varchar(100)")]
    public string hi_sqlTableName { get; set; }

    [Column(TypeName = "varchar(100)")]
    public string hi_sqlColumnName { get; set; }

    public string hi_conteudoAnterior { get; set; }

    public string hi_conteudoNovo { get; set; }

    public long? fk_tb_est { get; set; }

    public long? fk_tb_ator { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_historico")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }

    [ForeignKey("fk_tb_est")]
    [InverseProperty("tb_historico")]
    public virtual tb_est fk_tb_estNavigation { get; set; }
}