// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_est", Name = "ifk_tb_est_tb_jornada")]
[Index("fk_tb_pdv", Name = "ifk_tb_pdv_tb_jornada")]
public partial class tb_jornada
{
    [Key]
    public long id_jornada { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] jo_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] jo_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] jo_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] jo_desat { get; set; }

    [Column(TypeName = "bigint")]
    public long jo_numSeq { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] jo_aberta { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] jo_canc { get; set; }

    public long? fk_tb_pdv { get; set; }

    public long? fk_tb_est { get; set; }

    [ForeignKey("fk_tb_est")]
    [InverseProperty("tb_jornada")]
    public virtual tb_est fk_tb_estNavigation { get; set; }

    [ForeignKey("fk_tb_pdv")]
    [InverseProperty("tb_jornada")]
    public virtual tb_pdv fk_tb_pdvNavigation { get; set; }

    [InverseProperty("fk_tb_jornadaNavigation")]
    public virtual ICollection<tb_movimentacao> tb_movimentacao { get; set; } = new List<tb_movimentacao>();
}