// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_movimentacao", Name = "ifk_tb_movimentacao_tb_movimentacao_pagamento")]
[Index("fk_tb_sub_forma_pagamento", Name = "ifk_tb_sub_forma_pagamento_tb_movimentacao_pagamento")]
public partial class tb_movimentacao_pagamento
{
    [Key]
    public long id_movimentacao_pagamento { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mpg_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mpg_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] mpg_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] mpg_canc { get; set; }

    [Column(TypeName = "smallint")]
    public long mpg_numPag { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mpg_parcs { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mpg_nfeVlrPag { get; set; }

    [Column(TypeName = "tinyint")]
    public long mpg_nfeTipoIntegr { get; set; }

    [Column(TypeName = "tinyint")]
    public long mpg_nfeTipoBand { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string mpg_nfeNumAut { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mpg_nfeVlrTroco { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mpg_nfeVlrMov { get; set; }

    public long? fk_tb_movimentacao { get; set; }

    public long? fk_tb_sub_forma_pagamento { get; set; }

    [ForeignKey("fk_tb_movimentacao")]
    [InverseProperty("tb_movimentacao_pagamento")]
    public virtual tb_movimentacao fk_tb_movimentacaoNavigation { get; set; }

    [ForeignKey("fk_tb_sub_forma_pagamento")]
    [InverseProperty("tb_movimentacao_pagamento")]
    public virtual tb_sub_forma_pagamento fk_tb_sub_forma_pagamentoNavigation { get; set; }

    [InverseProperty("fk_tb_movimentacao_pagamentoNavigation")]
    public virtual ICollection<tb_movimentacao_pagamento_parcela> tb_movimentacao_pagamento_parcela { get; set; } = new List<tb_movimentacao_pagamento_parcela>();
}