// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_rede", Name = "ifk_tb_rede_tb_marca_produto")]
public partial class tb_marca_produto
{
    [Key]
    public long id_marca_produto { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mp_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mp_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] mp_dtAcs { get; set; }

    public long? mp_desat { get; set; }

    [Column(TypeName = "varchar(48)")]
    public string mp_desc { get; set; }

    public long? fk_tb_rede { get; set; }

    [ForeignKey("fk_tb_rede")]
    [InverseProperty("tb_marca_produto")]
    public virtual tb_rede fk_tb_redeNavigation { get; set; }

    [InverseProperty("fk_tb_matrizNavigation")]
    public virtual ICollection<tb_est> tb_est { get; set; } = new List<tb_est>();

    [InverseProperty("fk_tb_marca_produtoNavigation")]
    public virtual ICollection<tb_produto> tb_produto { get; set; } = new List<tb_produto>();
}