// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_estados_br", Name = "ifk_tb_estados_br_tb_municipio")]
public partial class tb_municipio
{
    [Key]
    public long id_municipio { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] mu_desat { get; set; }

    [Column(TypeName = "INT")]
    public long? mu_id { get; set; }

    [Column(TypeName = "varchar(40)")]
    public string mu_nome { get; set; }

    public long? fk_tb_estados_br { get; set; }

    [ForeignKey("fk_tb_estados_br")]
    [InverseProperty("tb_municipio")]
    public virtual tb_estados_br fk_tb_estados_brNavigation { get; set; }

    [InverseProperty("fk_tb_municipioNavigation")]
    public virtual ICollection<tb_ator> tb_ator { get; set; } = new List<tb_ator>();
}