// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_movimentacao", Name = "ifk_tb_movimentacao_tb_movimentacao_impressao")]
public partial class tb_movimentacao_impressao
{
    [Key]
    public long id_movimentacao_impressao { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mi_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mi_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] mi_dtAcs { get; set; }

    [Column(TypeName = "tinyint")]
    public long mi_tipo { get; set; }

    public byte[] mi_pdf { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] mi_dcanc { get; set; }

    public long? fk_tb_movimentacao { get; set; }

    [ForeignKey("fk_tb_movimentacao")]
    [InverseProperty("tb_movimentacao_impressao")]
    public virtual tb_movimentacao fk_tb_movimentacaoNavigation { get; set; }
}