// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_atorAtend", Name = "ifk_tb_atorAtend_tb_movimentacao_produto")]
[Index("fk_tb_movimentacao", Name = "ifk_tb_movimentacao_tb_movimentacao_produto")]
[Index("fk_tb_produto", Name = "ifk_tb_produto_tb_movimentacao_produto")]
public partial class tb_movimentacao_produto
{
    [Key]
    public long id_movimentacao_produto { get; set; }

    [Column(TypeName = "varchar(120)")]
    public string mp_desc { get; set; }

    [Column(TypeName = "varchar(25)")]
    public string mp_descCurta { get; set; }

    [Column(TypeName = "varchar(18)")]
    public string mp_nfeIpiCnpjProd { get; set; }

    [Column(TypeName = "varchar(8)")]
    public string mp_nfeNcm_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrFrete_ImpXml { get; set; }

    public long? mp_movProOrig { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mp_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mp_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] mp_dtAcs { get; set; }

    [Column(TypeName = "smallint")]
    public long mp_nfeCfop_ImpXml { get; set; }

    [Column(TypeName = "smallint")]
    public long mp_numItem { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] mp_canc { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfePisCofinsReg { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] mp_pisCofinsIncidencia { get; set; }

    [Column(TypeName = "bigint")]
    public long mp_codRef { get; set; }

    [Column(TypeName = "NUMERIC(13, 3)")]
    public byte[] mp_qtdCom { get; set; }

    public string mp_obs { get; set; }

    [Column(TypeName = "NUMERIC(13, 3)")]
    public byte[] mp_qtdDevolvida { get; set; }

    [Column(TypeName = "NUMERIC(13, 3)")]
    public byte[] mp_qtdDevolver { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_unMedCom { get; set; }

    [Column(TypeName = "varchar(10)")]
    public string mp_unMedCom_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrUnCom { get; set; }

    [Column(TypeName = "varchar(15)")]
    public string mp_ean { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrProdTot { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrProdTot_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrFrete { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrSeg { get; set; }

    [Column(TypeName = "nchar(1)")]
    public string mp_tipoDesc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrDesc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_vlrOutro { get; set; }

    [Column(TypeName = "varchar(7)")]
    public string mp_cest { get; set; }

    [Column(TypeName = "INT")]
    public long mp_nfeCfop { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfeIndValProdTotNfe { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfeProdOrigem { get; set; }

    [Column(TypeName = "smallint")]
    public long mp_nfeCst { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfeModBc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcIcms { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcIcms_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfeAliqIcms { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrTotIcms { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrTotIcms_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcFcp { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcFcp_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercFcp { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrFcp { get; set; }

    [Column(TypeName = "INT")]
    public long mp_nfeModBcSt { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercMvaSt { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercRedBcIcms { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercRedBcIcmsSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcIcmsSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcIcmsSt_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfeAliqIcmsSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsSt_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcFcpRetSt { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercFcpRetSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrFcpRetSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsDeson { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsDeson_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfeMotDesonIcms { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsOp { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsOp_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercDif { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsDif { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsDif_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcIcmsStRet { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercAliqSuportada { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsPropSubst { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsStRet { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeBcFcpRetAnt { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercFcpRetAntSt { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercRedBcEfet { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcEfet { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercAliqIcmsEfet { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsEfet { get; set; }

    [Column(TypeName = "smallint")]
    public long mp_nfeCsosn { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mp_nfePercAliqCredSn { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrCredIcmsSn { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string mp_nfeIpiCSelo { get; set; }

    [Column(TypeName = "INT")]
    public long mp_nfeIpiQSelo { get; set; }

    [Column(TypeName = "varchar(3)")]
    public string mp_nfeIpicEnq { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfeIpiTribCst { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeIpiTribXml1VlrBC { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeIpiTribXml1VlrBC_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeIpiTribXml1PercIPI { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeIpiTribXml2qUnid { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeIpiTribXml2VlrUnit { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeIpiTribXml2VlrIpi { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeIpiTribXml2VlrIpi_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfeIpiIpintCst { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeImpImpVlrBc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeImpImpVlrDespAdu { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeImpImpVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeImpImpVlrIof { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcIcmsUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcIcmsUfDest_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcFcpUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrBcFcpUfDest_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePercFcpUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeAliqIcmsUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeAliqIcmsInterUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePercIcmsPartUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrFcpUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsUfDest_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsUfRemet { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeVlrIcmsUfRemet_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long mp_nfePisCofinsCst { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliqVlrBc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliqVlrBc_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliq { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliq_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliqVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliqVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisQtdeBcProd { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisQtdeAliqProd { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisQtdeVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisQtdeVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisOutrBcVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisOutrBcVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisOutrAliq { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisOutrAliq_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisOutrVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisOutrVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisVlrBcST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisVlrBcST_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliqST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisQtdeBcProdST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisQtdeBcProdST_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisAliqProdST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisVlrST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfePisVlrST_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliqVlrBc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliqVlrBc_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliq { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliq_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliqVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliqVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsQtdeBcProd { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsQtdeBcProd_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsQtdeAliqProd { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsQtdeVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsQtdeVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrBcVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrBcVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrAliq { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrAliq_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrBcProd { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrBcProd_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrAliqProd { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrVlr { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsOutrVlr_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsVlrBcST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsVlrBcST_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliqST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsQtdeBcProdST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsQtdeBcProdST_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsAliqProdST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsVlrST { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_nfeCofinsVlrST_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mp_qtdAud { get; set; }

    public long? fk_tb_movimentacao { get; set; }

    public long? fk_tb_ncm { get; set; }

    public long? fk_tb_atorAtend { get; set; }

    public long? fk_tb_produto { get; set; }

    [ForeignKey("fk_tb_atorAtend")]
    [InverseProperty("tb_movimentacao_produto")]
    public virtual tb_ator fk_tb_atorAtendNavigation { get; set; }

    [ForeignKey("fk_tb_movimentacao")]
    [InverseProperty("tb_movimentacao_produto")]
    public virtual tb_movimentacao fk_tb_movimentacaoNavigation { get; set; }

    [ForeignKey("fk_tb_produto")]
    [InverseProperty("tb_movimentacao_produto")]
    public virtual tb_produto fk_tb_produtoNavigation { get; set; }
}