// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_movimentacao_pagamento", Name = "ifk_tb_movimentacao_pagamento_tb_movimentacao_pagamento_parcela")]
[Index("fk_tb_sub_forma_pagamento", Name = "ifk_tb_sub_forma_pagamento_tb_movimentacao_pagamento_parcela")]
public partial class tb_movimentacao_pagamento_parcela
{
    [Key]
    public long id_movimentacao_pagamento_parcela { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mpp_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mpp_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] mpp_dtAcs { get; set; }

    [Column(TypeName = "smallint")]
    public long mpp_numParc { get; set; }

    [Column(TypeName = "smallint")]
    public long mpp_qtdParc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mpp_vlrCli { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] mpp_taxaParc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] mpp_vlrRec { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] mpp_dtVenc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] mpp_canc { get; set; }

    public long? fk_tb_movimentacao_pagamento { get; set; }

    public long? fk_tb_sub_forma_pagamento { get; set; }

    [ForeignKey("fk_tb_movimentacao_pagamento")]
    [InverseProperty("tb_movimentacao_pagamento_parcela")]
    public virtual tb_movimentacao_pagamento fk_tb_movimentacao_pagamentoNavigation { get; set; }

    [ForeignKey("fk_tb_sub_forma_pagamento")]
    [InverseProperty("tb_movimentacao_pagamento_parcela")]
    public virtual tb_sub_forma_pagamento fk_tb_sub_forma_pagamentoNavigation { get; set; }
}