// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

public partial class tb_ncm
{
    [Key]
    public long id_ncm { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] nc_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] nc_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nc_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nc_desat { get; set; }

    [Column(TypeName = "varchar(10)")]
    public string nc_anoDoAto { get; set; }

    [Column(TypeName = "INT")]
    public long nc_numAto { get; set; }

    public long? nc_parentOid { get; set; }

    [Column(TypeName = "varchar(2)")]
    public string nc_rootNcm { get; set; }

    [Column(TypeName = "varchar(8)")]
    public string nc_ncmBase { get; set; }

    [Column(TypeName = "varchar(8)")]
    public string nc_ncmFull { get; set; }

    [Column(TypeName = "varchar(2048)")]
    public string nc_desc { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] nc_dtIni { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] nc_dtFim { get; set; }

    [InverseProperty("fk_tb_ncmNavigation")]
    public virtual ICollection<tb_produto> tb_produto { get; set; } = new List<tb_produto>();

    [InverseProperty("fk_tb_NcmNavigation")]
    public virtual ICollection<tb_subcategoria_produto> tb_subcategoria_produto { get; set; } = new List<tb_subcategoria_produto>();
}