// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_movimentacao", Name = "ifk_tb_movimentacao_tb_nfe")]
public partial class tb_nfe
{
    [Key]
    public long id_nfe { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeServico { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] nf_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] nf_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_dtAcs { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_desat { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_prontoEnviar { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string nf_nfeNatOp { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoAmb { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfeDtEmis { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfeDtAut { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeCfop { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeCst { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeCsosn { get; set; }

    [Column(TypeName = "varchar(15)")]
    public string nf_nfeNumProtAut { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeUf { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeCod { get; set; }

    [Column(TypeName = "varchar(50)")]
    public string nf_nfeChave { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] nf_nfeVersao { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeMod { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoEmis { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipo { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeSit { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeIdentLocDestOp { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeCodMunFg { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoImpDanfe { get; set; }

    [Column(TypeName = "tinyint")]
    public long? nf_nfeChaveDv { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoDfe { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeFinEmis { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeIndOpConsumFin { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeIndPresCompEstMomOp { get; set; }

    [Column(TypeName = "varchar(255)")]
    public string nf_nfeXmlArqAutPath { get; set; }

    public string nf_nfeXmlAutBkp { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeIndInterm { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeProcEmis { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string nf_nfeVerProcEmis { get; set; }

    public string nf_nfeInfoCompl { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeBcIcms { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcms { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrIcmsDeson { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsFcp { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsInterUfDest { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsInterUfRem { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFcp { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrBcIcmsSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFcpSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFcpRetSt { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotProd { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_vlrTotPag { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFrete { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotSeg { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotDesc { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotImpImp { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIpi { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIpiDevol { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotPis { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotCofins { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotOutro { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotNF { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotTrib { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeModFrete { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeCstat { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeSerieProd { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeSerieHom { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeNumProd { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeNumHom { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeNum { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeSerie { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeSolTransm { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfeSolTransmDt { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTransmStatus { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeXmlAutErro { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeXmlCancErro { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeEnvSfz { get; set; }

    public string nf_nfeTransmCorrigir { get; set; }

    public string nf_nfeTransmLog { get; set; }

    public string nf_nfeDhRecbto { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeProcAutExHRes { get; set; }

    public string nf_nfeProcAutExMsg { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeHaProtSfz { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeRejSfz { get; set; }

    public string nf_nfeXmlEnv { get; set; }

    public string nf_nfeXmlCorrigir { get; set; }

    public string nf_nfeArqProcAutDist { get; set; }

    [Column(TypeName = "varchar(255)")]
    public string nf_nfeCamArqProcAutDist { get; set; }

    [Column(TypeName = "varchar(255)")]
    public string nf_nfeNomeArqProcAutDist { get; set; }

    public string nf_nfeXmlOrig { get; set; }

    public string nf_nfeXmlAss { get; set; }

    public string nf_nfeXmlRetWs { get; set; }

    public string nf_nfeXmlProcRes { get; set; }

    public string nf_nfeXmlProcAutDist { get; set; }

    public string nf_nfeXmlEvtCancDist { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoAmb_ImpXml { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfeDtEmis_ImpXml { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfeDtAut_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeCfop_ImpXml { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeCst_ImpXml { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeCsosn_ImpXml { get; set; }

    [Column(TypeName = "varchar(15)")]
    public string nf_nfeNumProtAut_ImpXml { get; set; }

    public long? nf_nfeUf_ { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeUf_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeCod_ImpXml { get; set; }

    [Column(TypeName = "varchar(50)")]
    public string nf_nfeChave_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] nf_nfeVersao_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeMod_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoEmis_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipo_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeSit_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeIdentLocDestOp_ImpXml { get; set; }

    public long? nf_nfeCodMunFg_ { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeCodMunFg_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoImpDanfe_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long? nf_nfeChaveDv_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTipoDfe_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeFinEmis_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeIndOpConsumFin_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeIndPresCompEstMomOp_ImpXml { get; set; }

    [Column(TypeName = "varchar(255)")]
    public string nf_nfeXmlArqAutPath_ImpXml { get; set; }

    public string nf_nfeXmlAutBkp_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeIndInterm_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeProcEmis_ImpXml { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string nf_nfeVerProcEmis_ImpXml { get; set; }

    public string nf_nfeInfoCompl_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeBcIcms_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcms_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrIcmsDeson_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsFcp_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsInterUfDest_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsInterUfRem_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFcp_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrBcIcmsSt_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIcmsSt_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFcpSt_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFcpRetSt_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotProd_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_vlrTotPag_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotFrete_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotSeg_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotDesc_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotImpImp_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIpi_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotIpiDevol_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotPis_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotCofins_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotOutro_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotNF_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTotTrib_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeModFrete_ImpXml { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeCstat_ImpXml { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeSerieProd_ImpXml { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeSerieHom_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeNumProd_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeNumHom_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeNum_ImpXml { get; set; }

    [Column(TypeName = "smallint")]
    public long nf_nfeSerie_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeSolTransm_ImpXml { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfeSolTransmDt_ImpXml { get; set; }

    [Column(TypeName = "tinyint")]
    public long nf_nfeTransmStatus_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeXmlAutErro_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeXmlCancErro_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeEnvSfz_ImpXml { get; set; }

    public string nf_nfeTransmCorrigir_ImpXml { get; set; }

    public string nf_nfeTransmLog_ImpXml { get; set; }

    public string nf_nfeDhRecbto_ImpXml { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeProcAutExHRes_ImpXml { get; set; }

    public string nf_nfeProcAutExMsg_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeHaProtSfz_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] nf_nfeRejSfz_ImpXml { get; set; }

    public string nf_nfeXmlEnv_ImpXml { get; set; }

    public string nf_nfeXmlCorrigir_ImpXml { get; set; }

    public string nf_nfeArqProcAutDist_ImpXml { get; set; }

    [Column(TypeName = "varchar(255)")]
    public string nf_nfeCamArqProcAutDist_ImpXml { get; set; }

    [Column(TypeName = "varchar(255)")]
    public string nf_nfeNomeArqProcAutDist_ImpXml { get; set; }

    public string nf_nfeXmlOrig_ImpXml { get; set; }

    public string nf_nfeXmlAss_ImpXml { get; set; }

    public string nf_nfeXmlRetWs_ImpXml { get; set; }

    public string nf_nfeXmlProcRes_ImpXml { get; set; }

    public string nf_nfeXmlProcAutDist_ImpXml { get; set; }

    public string nf_nfeXmlEvtCancDist_ImpXml { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] nf_nfeVlrTroco_ImpXml { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfe1DhRecbto { get; set; }

    [Column(TypeName = "INT")]
    public long? nf_nfe1CStat { get; set; }

    public string nf_nfe1XMotivo { get; set; }

    public string nf_nfe1RetornoWSString { get; set; }

    public string nf_nfe1WSXMLInnerText { get; set; }

    public string nf_nfe1ConteudoXMLOriginalOuterXml { get; set; }

    [Column(TypeName = "INT")]
    public long? nf_nfe1ResProtNFeInfProt0CStat { get; set; }

    public string nf_nfe1ResProtNFeInfProt0ChNFe { get; set; }

    public string nf_nfe1ResProtNFeInfProt0XMotivo { get; set; }

    [Column(TypeName = "varchar(30)")]
    public string nf_nfe1ResProtNFeInfProt0NProt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfe1ResProtNFeInfProt0DhRecbto { get; set; }

    public string nf_nfe2ConteudoXMLOuterXml { get; set; }

    public string nf_nfe2RetornoWSString { get; set; }

    public string nf_nfe2RetornoWSXMLInnerText { get; set; }

    [Column(TypeName = "INT")]
    public long? nf_nfe2ResCStat { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfe2ResDhRecbto { get; set; }

    public string nf_nfe2ResNRec { get; set; }

    [Column(TypeName = "INT")]
    public long? nf_nfe2ResProtNFeInfProt0CStat { get; set; }

    public string nf_nfe2ResProtNFeInfProt0ChNFe { get; set; }

    public string nf_nfe2ResProtNFeInfProt0XMotivo { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] nf_nfe2ResProtNFeInfProt0DhRecbto { get; set; }

    public string nf_nfeProcResultsXMLDist { get; set; }

    [Column(TypeName = "INT")]
    public long nf_nfeProdNumPulo { get; set; }

    public long? fk_tb_movimentacao { get; set; }

    [ForeignKey("fk_tb_movimentacao")]
    [InverseProperty("tb_nfe")]
    public virtual tb_movimentacao fk_tb_movimentacaoNavigation { get; set; }

    [InverseProperty("fk_tb_nfeNavigation")]
    public virtual ICollection<tb_nfe_enviada_filial> tb_nfe_enviada_filial { get; set; } = new List<tb_nfe_enviada_filial>();
}