// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_produto_filial")]
[Index("fk_tb_produto", Name = "ifk_tb_produto_tb_produto_filial")]
public partial class tb_produto_filial
{
    [Key]
    public long id_produto_filial { get; set; }

    [Column(TypeName = "bigint")]
    public long pf_codRef { get; set; }

    [Column(TypeName = "varchar(120)")]
    public string pf_desc { get; set; }

    [Column(TypeName = "varchar(25)")]
    public string pf_descCurta { get; set; }

    [Column(TypeName = "tinyint")]
    public long? pf_proTipo { get; set; }

    [Column(TypeName = "tinyint")]
    public long pf_unMedCom { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime pf_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime pf_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] pf_dtAcs { get; set; }

    public long? pf_atorFil { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public decimal? pf_vlrUnCom { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public decimal? pf_cstUnCom { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public decimal? pf_estMin { get; set; }

    [Column(TypeName = "money")]
    public decimal? pf_estMax { get; set; }

    [Column(TypeName = "NUMERIC(13, 3)")]
    public long pf_est { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public decimal? pf_desat { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public int pf_canc { get; set; }

    public long? fk_tb_produto { get; set; }

    public long? fk_tb_ator { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_produto_filial")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }

    [ForeignKey("fk_tb_produto")]
    [InverseProperty("tb_produto_filial")]
    public virtual tb_produto fk_tb_produtoNavigation { get; set; }

    [InverseProperty("fk_tb_produto_filialNavigation")]
    public virtual ICollection<tb_relacao_produto_cadastro_XML> tb_relacao_produto_cadastro_XML { get; set; } = new List<tb_relacao_produto_cadastro_XML>();
}