// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_produto")]
[Index("fk_tb_categoria_produto", Name = "ifk_tb_categoria_produto_tb_produto")]
[Index("fk_tb_est", Name = "ifk_tb_est_tb_produto")]
[Index("fk_tb_marca_produto", Name = "ifk_tb_marca_produto_tb_produto")]
[Index("fk_tb_ncm", Name = "ifk_tb_ncm_tb_produto")]
[Index("fk_tb_rede", Name = "ifk_tb_rede_tb_produto")]
[Index("fk_tb_relacao_produto_cadastro_XML", Name = "ifk_tb_relacao_produto_cadastro_XML_tb_produto")]
[Index("fk_tb_subcategoria_produto", Name = "ifk_tb_subcategoria_produto_tb_produto")]
public partial class tb_produto
{
    [Key]
    public long id_produto { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime pd_dtCri { get; set; }
    // public decimal pd_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime pd_dtAlt { get; set; }
    //  public decimal pd_dtAlt { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public decimal? pd_desat { get; set; }

    [Column(TypeName = "tinyint")]
    public long pd_genero { get; set; }

    [Column(TypeName = "tinyint")]
    public long pd_unMedCom { get; set; }

    [Column(TypeName = "bigint")]
    public long pd_codRef { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string? pd_codRefStr { get; set; }

    [Column(TypeName = "varchar(512)")]
    public string? pd_barras { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string? pd_impRef { get; set; }

    [Column(TypeName = "tinyint")]
    public long? pd_proTipo { get; set; }

    [Column(TypeName = "tinyint")]
    public long? pd_especie { get; set; }

    [Column(TypeName = "NUMERIC(13, 3)")]
    public decimal? pd_estTot { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public decimal? pd_invend { get; set; }

    // [Required(ErrorMessage = "A descrição curta é obrigatória.")]
    [Column(TypeName = "varchar(25)")]
    public string pd_descCurta { get; set; }

    // [Required(ErrorMessage = "A descrição é obrigatória.")]
    [Column(TypeName = "varchar(120)")]
    public string pd_desc { get; set; }

    [Column(TypeName = "tinyint")]
    public long pd_fxEta { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public decimal? pd_vlrUnComBase { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public decimal? pd_cstUnComBase { get; set; }

    [Column(TypeName = "NUMERIC(13, 3)")]
    public decimal pd_estMinBase { get; set; }

    [Column(TypeName = "NUMERIC(13, 3)")]
    public decimal? pd_estMaxBase { get; set; }

    [Column(TypeName = "tinyint")]
    public long pd_nfeProdOrigem { get; set; }

    [Column(TypeName = "smallint")]
    public long pd_nfeCsosn { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public decimal? pd_vend { get; set; }

    public string pd_tmpStr { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public decimal? pd_ativo { get; set; }

    public long? fk_tb_est { get; set; }

    public long? fk_tb_rede { get; set; }

    public long? fk_tb_ncm { get; set; }

    public long? fk_tb_ator { get; set; }

    public long? fk_tb_relacao_produto_cadastro_XML { get; set; }

    public long? fk_tb_marca_produto { get; set; }

    public long? fk_tb_subcategoria_produto { get; set; }

    public long? fk_tb_categoria_produto { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_produto")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }

    [ForeignKey("fk_tb_categoria_produto")]
    [InverseProperty("tb_produto")]
    public virtual tb_categoria_produto fk_tb_categoria_produtoNavigation { get; set; }

    [ForeignKey("fk_tb_est")]
    [InverseProperty("tb_produto")]
    public virtual tb_est fk_tb_estNavigation { get; set; }

    [ForeignKey("fk_tb_marca_produto")]
    [InverseProperty("tb_produto")]
    public virtual tb_marca_produto fk_tb_marca_produtoNavigation { get; set; }

    [ForeignKey("fk_tb_ncm")]
    [InverseProperty("tb_produto")]
    public virtual tb_ncm fk_tb_ncmNavigation { get; set; }

    [ForeignKey("fk_tb_rede")]
    [InverseProperty("tb_produto")]
    public virtual tb_rede fk_tb_redeNavigation { get; set; }

    [ForeignKey("fk_tb_relacao_produto_cadastro_XML")]
    [InverseProperty("tb_produto")]
    public virtual tb_relacao_produto_cadastro_XML fk_tb_relacao_produto_cadastro_XMLNavigation { get; set; }

    [ForeignKey("fk_tb_subcategoria_produto")]
    [InverseProperty("tb_produto")]
    public virtual tb_subcategoria_produto fk_tb_subcategoria_produtoNavigation { get; set; }

    [InverseProperty("fk_tb_produtoNavigation")]
    public virtual ICollection<tb_codigo_produto> tb_codigo_produto { get; set; } = new List<tb_codigo_produto>();

    [InverseProperty("fk_tb_produtoNavigation")]
    public virtual ICollection<tb_movimentacao_produto> tb_movimentacao_produto { get; set; } = new List<tb_movimentacao_produto>();

    [InverseProperty("fk_tb_produtoNavigation")]
    public virtual ICollection<tb_produto_filial> tb_produto_filial { get; set; } = new List<tb_produto_filial>();

    [InverseProperty("fk_tb_produtoNavigation")]
    public virtual ICollection<tb_relacao_produto_cadastro_XML> tb_relacao_produto_cadastro_XML { get; set; } = new List<tb_relacao_produto_cadastro_XML>();
}