// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_pais", Name = "ifk_tb_pais_tb_regioes_br")]
public partial class tb_regioes_br
{
    [Key]
    public long id_regioes_br { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] rb_desat { get; set; }

    [Column(TypeName = "tinyint")]
    public long? rb_id { get; set; }

    [Column(TypeName = "varchar(2)")]
    public string rb_sigla { get; set; }

    [Column(TypeName = "varchar(12)")]
    public string rb_nome { get; set; }

    public long? fk_tb_pais { get; set; }

    [ForeignKey("fk_tb_pais")]
    [InverseProperty("tb_regioes_br")]
    public virtual tb_pais fk_tb_paisNavigation { get; set; }

    [InverseProperty("fk_tb_regioes_brNavigation")]
    public virtual ICollection<tb_estados_br> tb_estados_br { get; set; } = new List<tb_estados_br>();
}