// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_relacao_produto_cadastro_XML")]
[Index("fk_tb_produto_filial", Name = "ifk_tb_produto_filial_tb_relacao_produto_cadastro_XML")]
[Index("fk_tb_produto", Name = "ifk_tb_produto_tb_relacao_produto_cadastro_XML")]
public partial class tb_relacao_produto_cadastro_XML
{
    [Key]
    public long id_relacao_produto_cadastro_XML { get; set; }

    [Column(TypeName = "bigint")]
    public long rpc_codRef { get; set; }

    [Column(TypeName = "varchar(48)")]
    public string rpc_desc { get; set; }

    [Column(TypeName = "varchar(18)")]
    public string rpc_cnpj_fornecedor { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] rpc_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] rpc_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] rpc_dtAcs { get; set; }

    public long? fk_tb_produto { get; set; }

    public long? fk_tb_produto_filial { get; set; }

    public long? fk_tb_ator { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_relacao_produto_cadastro_XML")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }

    [ForeignKey("fk_tb_produto")]
    [InverseProperty("tb_relacao_produto_cadastro_XML")]
    public virtual tb_produto fk_tb_produtoNavigation { get; set; }

    [ForeignKey("fk_tb_produto_filial")]
    [InverseProperty("tb_relacao_produto_cadastro_XML")]
    public virtual tb_produto_filial fk_tb_produto_filialNavigation { get; set; }

    [InverseProperty("fk_tb_relacao_produto_cadastro_XMLNavigation")]
    public virtual ICollection<tb_produto> tb_produto { get; set; } = new List<tb_produto>();
}