// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_resposta_NFe")]
public partial class tb_resposta_NFe
{
    [Key]
    public long id_resposta_NFe { get; set; }

    [Column(TypeName = "varchar(18)")]
    public string rnfe_cnpj { get; set; }

    [Column(TypeName = "varchar(14)")]
    public string rnfe_cpf { get; set; }

    [Column(TypeName = "varchar(20)")]
    public string rnfe_inscEst { get; set; }

    [Column(TypeName = "varchar(50)")]
    public string rnfe_nfeChave { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] rnfe_nfeDtAut { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] rnfe_nfeDtEmis { get; set; }

    [Column(TypeName = "varchar(15)")]
    public string rnfe_nfeNumProtAut { get; set; }

    [Column(TypeName = "tinyint")]
    public long rnfe_nfeSit { get; set; }

    [Column(TypeName = "tinyint")]
    public long rnfe_nfeTipo { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] rnfe_nfeVersao { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] rnfe_nfeVlrTotNF { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string rnfe_razSoc { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] rnfe_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] rnfe_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] rnfe_dtAcs { get; set; }

    [Column(TypeName = "bigint")]
    public long rnfe_nsu { get; set; }

    [Column(TypeName = "bigint")]
    public long rnfe_ultNsu { get; set; }

    [Column(TypeName = "bigint")]
    public long rnfe_maxNsu { get; set; }

    public long? fk_tb_ator { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_resposta_NFe")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }
}