// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_ator", Name = "ifk_tb_ator_tb_resEventoNFe")]
public partial class tb_resEventoNFe
{
    [Key]
    public long id_resEventoNFe { get; set; }

    [Column(TypeName = "varchar(18)")]
    public string ref_cnpj { get; set; }

    [Column(TypeName = "varchar(14)")]
    public string ref_cpf { get; set; }

    [Column(TypeName = "varchar(50)")]
    public string ref_nfeChave { get; set; }

    [Column(TypeName = "NUMERIC(6, 3)")]
    public byte[] ref_nfeVersao { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ref_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public byte[] ref_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public byte[] ref_dtAcs { get; set; }

    [Column(TypeName = "bigint")]
    public long ref_nsu { get; set; }

    [Column(TypeName = "smallint")]
    public long ref_codOrg { get; set; }

    [Required]
    [Column(TypeName = "TIMESTAMP(8)")]
    public byte[] ref_dtEvt { get; set; }

    [Column(TypeName = "INT")]
    public long ref_sTpEvt { get; set; }

    [Column(TypeName = "smallint")]
    public long ref_numSeqEvt { get; set; }

    [Column(TypeName = "varchar(60)")]
    public string ref_descEvt { get; set; }

    [Column(TypeName = "varchar(15)")]
    public string ref_nfeNumProtEvt { get; set; }

    public long? fk_tb_ator { get; set; }

    [ForeignKey("fk_tb_ator")]
    [InverseProperty("tb_resEventoNFe")]
    public virtual tb_ator fk_tb_atorNavigation { get; set; }
}