// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

[Index("fk_tb_Ncm", Name = "ifk_tb_Ncm_tb_subcategoria_produto")]
[Index("fk_tb_categoria_produto", Name = "ifk_tb_categoria_produto_tb_subcategoria_produto")]
public partial class tb_subcategoria_produto
{
    [Key]
    public long id_subcategoria_produto { get; set; }

    [Column(TypeName = "tinyint")]
    public long scp_nfePisCofinsReg { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime scp_dtCri { get; set; }

    [Required]
    [Column(TypeName = "DATETIME")]
    public DateTime scp_dtAlt { get; set; }

    [Column(TypeName = "DATETIME")]
    public DateTime? scp_dtAcs { get; set; }

    [Column(TypeName = "varchar(48)")]
    public string scp_desc { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public int scp_desat { get; set; }

    [Column(TypeName = "varchar(8)")]
    public string? scp_ncmNum { get; set; }

    [Column(TypeName = "smallint")]
    public long scp_nfeCsosn { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] scp_descMax { get; set; }

    public long? fk_tb_categoria_produto { get; set; }

    public long? fk_tb_Ncm { get; set; }

    [ForeignKey("fk_tb_Ncm")]
    [InverseProperty("tb_subcategoria_produto")]
    public virtual tb_ncm fk_tb_NcmNavigation { get; set; }

    [ForeignKey("fk_tb_categoria_produto")]
    [InverseProperty("tb_subcategoria_produto")]
    public virtual tb_categoria_produto fk_tb_categoria_produtoNavigation { get; set; }

    [InverseProperty("fk_tb_subcategoria_produtoNavigation")]
    public virtual ICollection<tb_produto> tb_produto { get; set; } = new List<tb_produto>();
}