// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Velzon.Models;

public partial class tb_unidade_monetaria
{
    [Key]
    public long id_unidade_monetaria { get; set; }

    [Column(TypeName = "smallint")]
    public long? un_id { get; set; }

    [Column(TypeName = "varchar(3)")]
    public string un_sigla { get; set; }

    [Column(TypeName = "varchar(256)")]
    public string un_nome { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] un_inter { get; set; }

    [Column(TypeName = "NUMERIC(13, 2)")]
    public byte[] un_cambio { get; set; }

    public double? un_cambioDt { get; set; }

    [Column(TypeName = "NUMERIC(1, 0)")]
    public byte[] un_canc { get; set; }

    [InverseProperty("fk_tb_unidade_monetariaNavigation")]
    public virtual ICollection<tb_pais> tb_pais { get; set; } = new List<tb_pais>();
}